### ISSUE TITLE
Use _min() instead of min()

### ISSUE THREAD

**Issue by stritti** [Pedroalbuquerque/ESP32PWM#1]
https://github.com/Pedroalbuquerque/ESP32PWM/blob/4e29db8996a66a2e2207262f466b9c2332615e5e/ESP32PWM.h#L42

To be more flexible `min()` should be replaced by `_min()`.

See also: https://github.com/esp8266/Arduino/issues/2073

**Comment by stritti** [comment]
Could you fix this. There are now compile errors with current version.

**Comment by Pedroalbuquerque** [comment]
Proposed fix implemented ;)

**Comment by silencekeeper** [comment]
Hello! There are still same compile error. I've spent some time to find this closed issue. Could you fix it again for future users?:)

**Comment by Pedroalbuquerque** [comment]
Hello Silencekeeper,

not sure what happened, I believe I had already corrected it.
Anyway I just push again the change , and check in the web.
I believe it will not longer be a problem.

thank you for the warning.
